#!/usr/bin/env python3
"""Render readable YAML acceptance scenarios into native Gherkin features."""

from __future__ import annotations

import argparse
import importlib
import re
from collections.abc import Sequence
from pathlib import Path
from typing import Any

GENERATED_PREFIX = "# Generated by code-discipline gherkin_yaml; source: "
STEP_KEYWORDS = {"given", "when", "then", "and", "but"}


def is_yaml_feature(path: Path) -> bool:
    return path.name.endswith((".feature.yaml", ".feature.yml"))


def runner_path(path: Path) -> Path:
    return path.with_suffix("") if is_yaml_feature(path) else path


def text_value(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{context}: expected nonempty text; quote numeric values")
    if any(character in value for character in ("\n", "\r", "\x00")):
        raise ValueError(f"{context}: text must stay on one line")
    return value


def list_value(value: Any, context: str) -> list[Any]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"{context}: expected a nonempty list")
    return value


def object_value(value: Any, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{context}: expected a mapping")
    return value


def schema(
    value: Any, context: str, required: set[str], optional: set[str]
) -> dict[str, Any]:
    result = object_value(value, context)
    missing = required - result.keys()
    unknown = result.keys() - required - optional
    if missing:
        raise ValueError(f"{context}: missing keys: {', '.join(sorted(missing))}")
    if unknown:
        raise ValueError(f"{context}: unknown keys: {', '.join(sorted(unknown))}")
    return result


def unique_mapping(loader: Any, node: Any, deep: bool = False) -> dict[str, Any]:
    loader.flatten_mapping(node)
    result: dict[str, Any] = {}
    for key_node, value_node in node.value:
        key = text_value(loader.construct_object(key_node, deep=deep), "mapping key")
        if key in result:
            raise ValueError(f"duplicate YAML key: {key}")
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ValueError(f"cannot read {path}: {error}") from error


def load_yaml(path: Path) -> Any:
    try:
        yaml = importlib.import_module("yaml")
    except ImportError as error:
        raise ValueError("YAML authoring requires PyYAML==6.0.3") from error
    loader = type(
        "UniqueSafeLoader", (yaml.SafeLoader,), {"construct_mapping": unique_mapping}
    )
    try:
        return yaml.load(read_text(path), Loader=loader)
    except yaml.YAMLError as error:
        raise ValueError(f"invalid YAML: {error}") from error


def tag_lines(value: Any, indent: str) -> list[str]:
    tags = [text_value(tag, "tag") for tag in list_value(value, "tags")]
    if any(re.fullmatch(r"@[^\s@]+", tag) is None for tag in tags):
        raise ValueError("tags must start with @ and contain no whitespace or extra @")
    return [indent + " ".join(tags)]


def description_lines(value: Any) -> list[str]:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("description: expected nonempty text")
    return ["  # " + line for line in value.splitlines()]


def step_lines(value: Any, indent: str) -> list[str]:
    lines = []
    for item in list_value(value, "steps"):
        step = object_value(item, "step")
        if len(step) != 1 or not step.keys() <= STEP_KEYWORDS:
            raise ValueError("each step needs exactly one given/when/then/and/but key")
        keyword, text = next(iter(step.items()))
        lines.append(f"{indent}{keyword.title()} {text_value(text, 'step')}")
    return lines


def example_cell(value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("Examples cell: expected nonempty text; quote numeric values")
    if "\r" in value or "\x00" in value:
        raise ValueError("Examples cell: carriage returns and null bytes are invalid")
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", "\\n")


def table_line(values: Sequence[Any]) -> str:
    return "      | " + " | ".join(example_cell(value) for value in values) + " |"


def example_lines(value: Any) -> list[str]:
    rows = [object_value(row, "Examples row") for row in list_value(value, "examples")]
    columns = list(rows[0])
    if not columns:
        raise ValueError("Examples rows need at least one column")
    lines = ["    Examples:", table_line(columns)]
    for row in rows:
        if row.keys() != rows[0].keys():
            raise ValueError("all Examples rows must use the same columns")
        lines.append(table_line([row[column] for column in columns]))
    return lines


def scenario_lines(value: Any) -> list[str]:
    scenario = schema(value, "scenario", {"name", "steps"}, {"tags", "examples"})
    lines = [""]
    if "tags" in scenario:
        lines.extend(tag_lines(scenario["tags"], "  "))
    kind = "Scenario Outline" if "examples" in scenario else "Scenario"
    lines.append(f"  {kind}: {text_value(scenario['name'], 'scenario name')}")
    lines.extend(step_lines(scenario["steps"], "    "))
    if "examples" in scenario:
        lines.extend(example_lines(scenario["examples"]))
    return lines


def document_lines(document: Any, source_name: str) -> list[str]:
    feature = schema(
        document,
        "feature",
        {"feature", "scenarios"},
        {"description", "tags", "background"},
    )
    lines = [GENERATED_PREFIX + text_value(source_name, "source filename")]
    if "tags" in feature:
        lines.extend(tag_lines(feature["tags"], ""))
    lines.append("Feature: " + text_value(feature["feature"], "feature name"))
    if "description" in feature:
        lines.extend(description_lines(feature["description"]))
    if "background" in feature:
        lines.extend(["", "  Background:", *step_lines(feature["background"], "    ")])
    for scenario in list_value(feature["scenarios"], "scenarios"):
        lines.extend(scenario_lines(scenario))
    return lines


def render_feature(path: Path) -> str:
    if not is_yaml_feature(path):
        raise ValueError(f"{path}: expected a .feature.yaml or .feature.yml source")
    try:
        return "\n".join(document_lines(load_yaml(path), path.name)) + "\n"
    except ValueError as error:
        raise ValueError(f"{path}: {error}") from error


def generated_source(path: Path) -> Path | None:
    first_line = read_text(path).partition("\n")[0]
    if not first_line.startswith(GENERATED_PREFIX):
        return None
    name = first_line.removeprefix(GENERATED_PREFIX)
    source = path.parent / name
    if (
        source.name != name
        or not is_yaml_feature(source)
        or runner_path(source) != path
    ):
        raise ValueError(f"{path}: invalid generated-source marker")
    return source


def register_source(sources: dict[Path, Path], source: Path) -> None:
    target = runner_path(source)
    alternate_suffix = ".yml" if source.suffix == ".yaml" else ".yaml"
    if source.with_suffix(alternate_suffix).exists():
        raise ValueError(f"{source}: .yaml and .yml sources collide at {target}")
    if target in sources and sources[target] != source:
        raise ValueError(f"{source}: multiple YAML sources generate {target}")
    sources[target] = source


def inventory_sources(paths: Sequence[Path]) -> dict[Path, Path]:
    sources: dict[Path, Path] = {}
    for path in paths:
        register_input(sources, path)
    for path in paths:
        if path.suffix == ".feature" and path not in sources:
            register_generated(sources, path)
    return sources


def register_input(sources: dict[Path, Path], path: Path) -> None:
    if is_yaml_feature(path):
        register_source(sources, path)
    elif path.suffix != ".feature":
        raise ValueError(f"{path}: expected .feature.yaml, .feature.yml, or .feature")


def register_generated(sources: dict[Path, Path], path: Path) -> None:
    source = generated_source(path)
    if source is None:
        return
    if not source.is_file():
        raise ValueError(f"{path}: orphaned generated feature; restore {source}")
    register_source(sources, source)


def check_target(target: Path, source: Path) -> None:
    if not target.exists():
        return
    owner = generated_source(target)
    if owner != source:
        raise ValueError(
            f"{target}: refusing to overwrite an authored or differently owned feature"
        )


def write_feature(path: Path, content: str) -> None:
    try:
        path.write_text(content, encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ValueError(f"cannot write generated feature {path}: {error}") from error


def prepare_features(paths: Sequence[Path]) -> list[Path]:
    resolved = list(dict.fromkeys(path.resolve() for path in paths))
    sources = inventory_sources(resolved)
    rendered = {}
    for target, source in sources.items():
        check_target(target, source)
        rendered[target] = render_feature(source)
    for target, content in rendered.items():
        write_feature(target, content)
    return list(dict.fromkeys(runner_path(path) for path in resolved))


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--feature", action="append", required=True, type=Path)
    arguments = parser.parse_args(argv)
    try:
        paths = prepare_features([arguments.root / path for path in arguments.feature])
    except ValueError as error:
        print(f"Gherkin YAML preparation failed: {error}")
        return 1
    print(f"Prepared {len(paths)} executable Gherkin feature(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
